version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 18675206891
      MYSQL_DATABASE: mygpt
      MYSQL_USER: root
      MYSQL_PASSWORD: 18675206891
    volumes:
      - dbdata:/var/lib/mysql

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis

volumes:
  dbdata: